version: '3.9'

services:
  fastapi-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: aireserve-app
    env_file:
      - ../.env
    ports:
      - "${FASTAPI_PORT}:8000"
    command: "sh /app/entrypoint.sh"
    depends_on:
      - postgres
    volumes:
      - ..:/app/
